### ISSUE TITLE
about pycrypto issues with python3

### ISSUE THREAD

**Issue by EeroV** [inode-/zyxel_password_decrypter#1]
If You are using python 3, then pycrypto does not work. Working replacement is: pycryptodome

This is just note for all.

**Comment by bovirus** [comment]
@EeroV 

How can modify .py script to sue in python 3?

How can create a standalone exe file that don't require python?

**Comment by EeroV** [comment]
https://www.baeldung.com/linux/python-binary

**Comment by bovirus** [comment]
@EeroV 

I already tried but I got this error running the exe

Traceback (most recent call last):
  File "zyxel_decrypter.py", line 35, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
[169684] Failed to execute script 'zyxel_decrypter' due to unhandled exception!

I tried with Python 3.12 or 3.13.

**Comment by EeroV** [comment]
as I said

If You are using python 3, then pycrypto does not work. Working replacement
is: pycryptodome

ask from AI / chatgpt how to do this

Eero

**Comment by EeroV** [comment]
installl pycryptopme and then it just works

https://www.odoo.com/forum/help-1/how-to-fix-no-module-named-crypto-244435

on my system: i run this command as root to fix issue

pip3 install pycryptodome --break-system-packages


Eero

ti 30.12.2025 klo 22.03 bovirus ***@***.***) kirjoitti:

**Comment by bovirus** [comment]
@EeroV 

pip3 install pycryptodome --break-system-packages
Requirement already satisfied: pycryptodome in c:\python313-32bit\lib\site-packages (3.23.0)

**pyinstaller zyxel_decrypter.py --onefile**
377 INFO: PyInstaller: 5.7.0
377 INFO: Python: 3.10.11
389 INFO: Platform: Windows-10-10.0.26200-SP0
390 INFO: wrote zyxel_decrypter.spec
405 INFO: UPX is not available.
408 INFO: Extending PYTHONPATH with paths
[Zyxel-decryper']
914 INFO: checking Analysis
914 INFO: Building Analysis because Analysis-00.toc is non existent
914 INFO: Initializing module dependency graph...
923 INFO: Caching module graph hooks...
996 INFO: Analyzing base_library.zip ...
3515 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Python310-64bit\\lib\\site-packages\\PyInstaller\\hooks'...
3680 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Python310-64bit\\lib\\site-packages\\PyInstaller\\hooks'...
6630 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Python310-64bit\\lib\\site-packages\\PyInstaller\\hooks'...
10304 INFO: Caching module dependency graph...
10458 INFO: running Analysis Analysis-00.toc
10464 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Python310-64bit\python.exe
10814 INFO: Analyzing D:\Download\Temp2\Zyxel-decryper\zyxel_decrypter.py
10840 INFO: Processing module hooks...
10859 INFO: Looking for ctypes DLLs
10862 INFO: Analyzing run-time hooks ...
10864 INFO: Including run-time hook 'C:\\Python310-64bit\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
10881 INFO: Looking for dynamic libraries
372 INFO: Extra DLL search directories (AddDllDirectory): []
372 INFO: Extra DLL search directories (PATH): ['C:\\Program Files\\Smart Projects\\IsoBuster', 'c:\\program files\\common files\\oracle\\java\\javapath', 'c:\\program files (x86)\\common files\\oracle\\java\\java8path', 'c:\\program files (x86)\\common files\\oracle\\java\\javapath', 'c:\\windows', 'c:\\windows\\system32\\wbem', 'c:\\windows\\system32\\windowspowershell\\v1.0\\', 'c:\\windows\\system32\\openssh\\', 'c:\\program files (x86)\\nvidia corporation\\physx\\common', 'c:\\windows\\system32', 'c:\\program files\\dotnet\\', 'c:\\program files\\java\\jre1.8.0_471\\bin', 'c:\\program files\\java\\jdk-1.8\\bin', 'c:\\program files (x86)\\common files\\divx shared\\desktopservice', 'c:\\program files\\git\\cmd', 'c:\\svabi\\files', 'c:\\program files\\docker\\docker\\resources\\bin', 'c:\\programdata\\chocolatey\\bin', 'c:\\program files\\lanalyze', 'c:\\program files (x86)\\common files\\divx11 shared\\desktopservice', 'c:\\program files\\microsoft sql server\\150\\tools\\binn\\', 'c:\\program files\\microsoft sql server\\130\\tools\\binn\\', 'c:\\program files (x86)\\easeus\\todo backup\\cmdtools', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\system32\\wbem', 'C:\\WINDOWS\\system32\\windowspowershell\\v1.0\\', 'C:\\WINDOWS\\system32\\openssh\\', 'c:\\program files (x86)\\nickvision parabolic\\release', 'c:\\program files (x86)\\nickvision parabolic\\release', 'c:\\program files (x86)\\nickvision parabolic\\release', 'c:\\program files\\powershell\\7\\', 'c:\\program files\\git\\cmd', 'c:\\program files\\docker\\docker\\resources\\bin', 'C:\\Program Files (x86)\\dotnet-core-uninstall\\', 'C:\\Program Files\\Git\\cmd', 'C:\\Program Files\\nodejs\\', 'C:\\Program Files\\CMake\\bin', 'C:\\Program Files (x86)\\HP\\IdrsOCR_15.4.1132.0\\', 'C:\\Program Files (x86)\\HP\\HP OCR\\DB_Lib\\', 'C:\\Program Files\\HP\\Common\\HPDestPlgIn\\', 'C:\\Program Files (x86)\\HP\\Common\\HPDestPlgIn\\', 'C:\\Program Files\\Docker\\Docker\\resources\\bin', 'C:\\Program Files\\Streamlink\\bin', 'C:\\Users\\Roberto\\AppData\\Local\\Programs\\Python\\Launcher\\', 'C:\\Tools\\gettext\\bin', 'C:\\Python313-32bit\\Scripts\\', 'C:\\Python313-32bit\\', 'C:\\Python312-32bit\\Scripts\\', 'C:\\Python312-32bit\\', 'C:\\Python312\\Scripts\\', 'C:\\Python312\\', 'C:\\Python312-64bit\\Scripts\\', 'C:\\Python312-64bit\\', 'C:\\Users\\Roberto\\scoop\\apps\\python\\current', 'C:\\Python310-64bit\\Scripts\\', 'C:\\Python310-64bit\\', 'C:\\Program Files (x86)\\NSIS 3\\Bin', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build', 'C:\\msys64\\mingw64\\share', 'C:\\Users\\Roberto\\.dotnet\\tools', 'C:\\msys64\\mingw64\\bin', 'C:\\Qt\\6.11.0\\msvc2022_64\\bin', 'C:\\Users\\Roberto\\scoop\\shims', 'C:\\Users\\Roberto\\AppData\\Local\\InfoCert\\GoSign Desktop\\RAOC:\\Users\\Roberto\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\Roberto\\AppData\\Local\\Programs\\Microsoft VS Code\\bin', 'C:\\Users\\Roberto\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\Roberto\\.dotnet\\tools', 'C:\\Users\\Roberto\\AppData\\Local\\Programs\\EmEditor', 'C:\\Users\\Roberto\\scoop\\apps\\python\\current\\Scripts', 'C:\\Users\\Roberto\\AppData\\Local\\Microsoft\\WinGet\\Links', 'C:\\Users\\Roberto\\AppData\\Local\\JSONBuddy', 'C:\\Program Files\\Java\\JDK-21', 'C:\\Program Files (x86)\\NSIS 2\\Bin', 'C:\\Tools', 'C:\\Users\\Roberto\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\Roberto\\AppData\\Roaming\\npm']
12059 INFO: Looking for eggs
12060 INFO: Using Python library C:\Python310-64bit\python310.dll
12061 INFO: Found binding redirects:
[]
12064 INFO: Warnings written to D:\Download\Temp2\Zyxel-decryper\build\zyxel_decrypter\warn-zyxel_decrypter.txt
12088 INFO: Graph cross-reference written to D:\Download\Temp2\Zyxel-decryper\build\zyxel_decrypter\xref-zyxel_decrypter.html
12171 INFO: checking PYZ
12171 INFO: Building PYZ because PYZ-00.toc is non existent
12173 INFO: Building PYZ (ZlibArchive) D:\Download\Temp2\Zyxel-decryper\build\zyxel_decrypter\PYZ-00.pyz
12452 INFO: Building PYZ (ZlibArchive) D:\Download\Temp2\Zyxel-decryper\build\zyxel_decrypter\PYZ-00.pyz completed successfully.
12459 INFO: checking PKG
12460 INFO: Building PKG because PKG-00.toc is non existent
12460 INFO: Building PKG (CArchive) zyxel_decrypter.pkg
14246 INFO: Building PKG (CArchive) zyxel_decrypter.pkg completed successfully.
14249 INFO: Bootloader C:\Python310-64bit\lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
14250 INFO: checking EXE
14250 INFO: Building EXE because EXE-00.toc is non existent
14250 INFO: Building EXE from EXE-00.toc
14251 INFO: Copying bootloader EXE to D:\Download\Temp2\Zyxel-decryper\dist\zyxel_decrypter.exe.notanexecutable
14367 INFO: Copying icon to EXE
14399 INFO: Copying icons from ['C:\\Python310-64bit\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
14456 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
14456 INFO: Writing RT_ICON 1 resource with 3752 bytes
14458 INFO: Writing RT_ICON 2 resource with 2216 bytes
14458 INFO: Writing RT_ICON 3 resource with 1384 bytes
14458 INFO: Writing RT_ICON 4 resource with 37019 bytes
14458 INFO: Writing RT_ICON 5 resource with 9640 bytes
14458 INFO: Writing RT_ICON 6 resource with 4264 bytes
14458 INFO: Writing RT_ICON 7 resource with 1128 bytes
14464 INFO: Copying 0 resources to EXE
14465 INFO: Embedding manifest in EXE
14465 INFO: Updating manifest in Zyxel-decryper\dist\zyxel_decrypter.exe.notanexecutable
14509 INFO: Updating resource type 24 name 1 language 0
14514 INFO: Appending PKG archive to EXE
14578 INFO: Fixing EXE headers
14835 INFO: Building EXE from EXE-00.toc completed successfully.

**zyxel_decrypter**
Traceback (most recent call last):
  **File "zyxel_decrypter.py", line 35, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'**
[23604] Failed to execute script 'zyxel_decrypter' due to unhandled exception!

**Comment by EeroV** [comment]
mine works fine

C:\Users\Eero\zyxel>pyinstaller zyxel.py --onefile
252 INFO: PyInstaller: 6.17.0, contrib hooks: 2025.11
252 INFO: Python: 3.13.7
277 INFO: Platform: Windows-11-10.0.26200-SP0
277 INFO: Python environment:
C:\Users\Eero\AppData\Local\Programs\Python\Python313
279 INFO: wrote C:\Users\Eero\zyxel\zyxel.spec
290 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\pyinstaller.exe',
 'C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip',
 'C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313\\DLLs',
 'C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313\\Lib',
 'C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313',
 'C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages',
 'C:\\Users\\Eero\\zyxel']
539 INFO: checking Analysis
539 INFO: Building Analysis because Analysis-00.toc is non existent
539 INFO: Looking for Python shared library...
540 INFO: Using Python shared library:
C:\Users\Eero\AppData\Local\Programs\Python\Python313\python313.dll
540 INFO: Running Analysis Analysis-00.toc
540 INFO: Target bytecode optimization level: 0
540 INFO: Initializing module dependency graph...
561 INFO: Initializing module graph hook caches...
590 INFO: Analyzing modules for base_library.zip ...
1550 INFO: Processing standard module hook 'hook-encodings.py' from
'C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\PyInstaller\\hooks'
3255 INFO: Processing standard module hook 'hook-pickle.py' from
'C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\PyInstaller\\hooks'
4030 INFO: Processing standard module hook 'hook-heapq.py' from
'C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\PyInstaller\\hooks'
4485 INFO: Caching module dependency graph...
4513 INFO: Analyzing C:\Users\Eero\zyxel\zyxel.py
C:\Users\Eero\zyxel\zyxel.py:82: SyntaxWarning: invalid escape sequence '\$'
  pattern = "\$.*?\$(.*?)\$(.*?)\$"
C:\Users\Eero\zyxel\zyxel.py:110: SyntaxWarning: invalid escape sequence
'\$'
  pattern = "\$.*?\$(.*?)\$(.*?)\$(.*?)\$"
4523 INFO: Processing standard module hook 'hook-Crypto.py' from
'C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\stdhooks'
4830 INFO: Processing standard module hook 'hook-_ctypes.py' from
'C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\PyInstaller\\hooks'
4882 INFO: Processing standard module hook 'hook-platform.py' from
'C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\PyInstaller\\hooks'
5059 INFO: Processing module hooks (post-graph stage)...
5066 INFO: Performing binary vs. data reclassification (43 entries)
7064 INFO: Looking for ctypes DLLs
7074 INFO: Analyzing run-time hooks ...
7075 INFO: Including run-time hook 'pyi_rth_inspect.py' from
'C:\\Users\\Eero\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks'
7080 INFO: Creating base_library.zip...
7099 INFO: Looking for dynamic libraries
7201 INFO: Extra DLL search directories (AddDllDirectory): []
7202 INFO: Extra DLL search directories (PATH): []
7373 INFO: Warnings written to
C:\Users\Eero\zyxel\build\zyxel\warn-zyxel.txt
7388 INFO: Graph cross-reference written to
C:\Users\Eero\zyxel\build\zyxel\xref-zyxel.html
7407 INFO: checking PYZ
7407 INFO: Building PYZ because PYZ-00.toc is non existent
7407 INFO: Building PYZ (ZlibArchive)
C:\Users\Eero\zyxel\build\zyxel\PYZ-00.pyz
7547 INFO: Building PYZ (ZlibArchive)
C:\Users\Eero\zyxel\build\zyxel\PYZ-00.pyz completed successfully.
7587 INFO: checking PKG
7588 INFO: Building PKG because PKG-00.toc is non existent
7588 INFO: Building PKG (CArchive) zyxel.pkg
C:\Users\Eero\zyxel\zyxel.py:82: SyntaxWarning: invalid escape sequence '\$'
  pattern = "\$.*?\$(.*?)\$(.*?)\$"
C:\Users\Eero\zyxel\zyxel.py:110: SyntaxWarning: invalid escape sequence
'\$'
  pattern = "\$.*?\$(.*?)\$(.*?)\$(.*?)\$"
9325 INFO: Building PKG (CArchive) zyxel.pkg completed successfully.
9327 INFO: Bootloader
C:\Users\Eero\AppData\Local\Programs\Python\Python313\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
9327 INFO: checking EXE
9327 INFO: Building EXE because EXE-00.toc is non existent
9327 INFO: Building EXE from EXE-00.toc
9327 INFO: Copying bootloader EXE to C:\Users\Eero\zyxel\dist\zyxel.exe
9590 INFO: Copying icon to EXE
9765 INFO: Copying 0 resources to EXE
9765 INFO: Embedding manifest in EXE
9892 INFO: Appending PKG archive to EXE
10318 INFO: Fixing EXE headers
15244 INFO: Building EXE from EXE-00.toc completed successfully.
15247 INFO: Build complete! The results are available in:
C:\Users\Eero\zyxel\dist

C:\Users\Eero\zyxel>



ke 31.12.2025 klo 9.38 bovirus ***@***.***) kirjoitti:

**Comment by EeroV** [comment]
you probably first need to fix that

python3 zyxel_decrypter.py

command works first.

Eero

ke 31.12.2025 klo 9.47 Eero Volotinen ***@***.***) kirjoitti:

**Comment by EeroV** [comment]
it might be wise to copy your output to chatgpt/copilot and ask how to fix
issue. it usually works :)

Eero

ke 31.12.2025 klo 9.38 bovirus ***@***.***) kirjoitti:

**Comment by bovirus** [comment]
@EeroV 

zyxel_decrypter.py:82: SyntaxWarning: invalid escape sequence '\$'
  pattern = "\$.*?\$(.*?)\$(.*?)\$"
zyxel_decrypter.py:110: SyntaxWarning: invalid escape sequence '\$'
  pattern = "\$.*?\$(.*?)\$(.*?)\$(.*?)\$"
Traceback (most recent call last):
  File "zyxel_decrypter.py", line 35, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

Could you please uplaod your zyxel_decrypter.exe in some host like mega or other?

Thanks.

**Comment by EeroV** [comment]
uploaded to binary to https://github.com/EeroV/zyxel-compiled @bovirus
